### ISSUE TITLE
Issue with specific string

### ISSUE THREAD

**Issue by en3sis** [breitburg/domine#1]
Hello,

I want to start by giving you some kudos, an awesome little tool =)!

It seems that for some reason, the `vac.*` will fail with the following error: 
![image](https://github.com/breitburg/domine/assets/940170/c27cf6f4-28d1-47b7-996c-33ce97825be8)

**Comment by breitburg** [comment]
Hello! Thank you for trying out the tool. I will look into this shortly and figure out a solution.

**Comment by breitburg** [comment]
I believe I have found the problem. I have published a fix to the [Docker Hub](https://hub.docker.com/r/breitburg/domine) and [Pub](https://pub.dev/packages/domine). @en3sis, could you please test it and provide feedback?

**Comment by en3sis** [comment]
I'm out for the week without access to my computer, I'll give it a try once back :)

**Comment by altirel** [comment]
Hey @breitburg, @en3sis I've pulled a new Docker image and now It works like this.   
  
Here is a screenshot of the result:  
<img width="610" alt="Снимок экрана 2023-07-29 в 13 32 29" src="https://github.com/breitburg/domine/assets/14005254/fda5f07b-0508-4951-a23e-ee49ff177cf0">

**Comment by breitburg** [comment]
Bonjour @altirel! That's weird. It appears that Domine does not detect that it has a terminal to output and works in headless mode (as if you were writing it to a file through a pipe). I'll look into that soon.

**Comment by breitburg** [comment]
Okay, I guess @en3sis will not show up. Please reopen the issue if necessary.
