### ISSUE TITLE
Incorrect headless mode detection while using with Docker

### ISSUE THREAD

**Issue by breitburg** [breitburg/domine#4]
Hey @breitburg, @en3sis I've pulled a new Docker image and now It works like this.   
  
Here is a screenshot of the result:  
<img width="610" alt="Снимок экрана 2023-07-29 в 13 32 29" src="https://github.com/breitburg/domine/assets/14005254/fda5f07b-0508-4951-a23e-ee49ff177cf0">

_Originally posted by @altirel in https://github.com/breitburg/domine/issues/1#issuecomment-1656690810_

**Comment by breitburg** [comment]
@altirel can you please try adding `--tty` flag to the command.

```console
$ docker run --rm --tty breitburg/domine check "vac.*"
```

**Comment by altirel** [comment]
@breitburg yeah, sure. It works as it is supposed to.  
Here is a screenshot:  
<img width="680" alt="Снимок экрана 2023-08-01 в 22 23 08" src="https://github.com/breitburg/domine/assets/14005254/3d84e605-9a3b-4071-be74-07c152c8d1fb">

**Comment by breitburg** [comment]
Okay, awesome. Thank you for using the tool.
